### ISSUE TITLE
interpreter

### ISSUE THREAD

**Issue by lgcardeas** [LorenzoBettini/Xtext-Buckminster-Example#1]
Hello .. I need to know if in the process of interpreting. I can display a window to alter the value of a variable. thank you

**Comment by LorenzoBettini** [comment]
mh... I don't understand how this is related to this very example

**Comment by lgcardeas** [comment]
please sorry, i was wrong about the place where i put my question

**Comment by LorenzoBettini** [comment]
OK, so I consider this as closed
